### ISSUE TITLE
Type package in dependencies

### ISSUE THREAD

**Issue by fcollonval** [antongolub/tsc-esm-fix#113]
What is the reason for having `@types/fs-extra` as dependencies and not devDependencies?

https://github.com/antongolub/tsc-esm-fix/blob/e3eb919439e33ff846d1b6b94e3ede0e2d2eb4e2/package.json#L56

**Comment by antongolub** [comment]
My crooked hands is the only.

**Comment by antongolub** [comment]
Thanks for the repost. The fix is on the way.

**Comment by fcollonval** [comment]
Thanks a lot for the super fast reply and fix.
