### ISSUE TITLE
keep package import

### ISSUE THREAD

**Issue by milahu** [antongolub/tsc-esm-fix#130]
tsc-esm-fix does a wrong fix on [my code](https://github.com/milahu/nodejs-lockfile-parser/commit/e50189c9f175eace9740dd3b1dedb4dc67db4b64)

```diff
-import * as graphlib from '@snyk/graphlib';
+import * as graphlib from '@snyk/graphlib/index.js';
```

expected: the package import should be preserved

`@snyk/graphlib` is [installed](https://github.com/milahu/nodejs-lockfile-parser/blob/e50189c9f175eace9740dd3b1dedb4dc67db4b64/package.json#L37) as a top-level dependency

reproduce

```
cd $(mktemp -d)
wget https://github.com/milahu/nodejs-lockfile-parser/archive/e50189c9f175eace9740dd3b1dedb4dc67db4b64.tar.gz
tar xf *.tar.gz --strip-components=1
npm install --ignore-scripts
npm run tsc-esm-fix
grep @snyk/graphlib lib/parsers/lock-parser-base.ts
```

actual result

```
import * as graphlib from '@snyk/graphlib/index.js';
```

when i compile that code with `npm run build`, i get the build error

```
lib/parsers/lock-parser-base.ts:4:27 - error TS2306: File 'node_modules/@snyk/graphlib/index.d.ts' is not a module.

4 import * as graphlib from '@snyk/graphlib/index.js';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by antongolub** [comment]
Hey @milahu,

Thanks for the report. The patch is on the way
