### ISSUE TITLE
Does not transform the first line

### ISSUE THREAD

**Issue by ayonli** [antongolub/tsc-esm-fix#136]
The following are the compiled file's content:

```js
import "./string/augment";
import "./number/augment";
import "./array/augment";
import "./uint8array/augment";
import "./object/augment";
import "./math/augment";
import "./promise/augment";
import "./collections/augment";
import "./error/augment";
import jsext from "./index";
export default jsext;
//# sourceMappingURL=augment.js.map
```

After running `npx tsc-esm-fix --target=esm`, the content becomes:

```js
import "./string/augment";
import "./number/augment.js";
import "./array/augment.js";
import "./uint8array/augment.js";
import "./object/augment.js";
import "./math/augment.js";
import "./promise/augment.js";
import "./collections/augment.js";
import "./error/augment.js";
import jsext from "./index.js";
export default jsext;
//# sourceMappingURL=augment.js.map
```

The first line is not changed.

**Comment by antongolub** [comment]
Hey, @ayonli,

Could you provide a reproducible example for debug? This will help to locate the issue.

**Comment by ayonli** [comment]
@antongolub Sorry I have changed my repo's structure and now use **rollup** to transpile the code and it generated code with `.js` extensions already. But during my test, if I added a line before the first line, say a comment, then **tsc-esm-fix** could work as expected, hope this helps.

**Comment by antongolub** [comment]
@ayonli, I've found the problem. Thanks for the report!
