### ISSUE TITLE
2.20.16 Broke Something

### ISSUE THREAD

**Issue by pcfreak30** [antongolub/tsc-esm-fix#138]
`Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'X/node_modules/tsc-esm-fix/target/es6/meow.d.ts' imported from X/node_modules/tsc-esm-fix/target/es6/cli.mjs`

Manually overriding to .14 or .15 works, but .16 breaks something.

Using typescript 5.2.2.

**Comment by antongolub** [comment]
@pcfreak30,

Thanks for the report. The fix is on the way.
