### ISSUE TITLE
Encounter error when a package has a malformed package.json

### ISSUE THREAD

**Issue by alvis** [antongolub/tsc-esm-fix#154]
I've encountered a dependent dependency which has a malformed exports fields in package.json
https://github.com/toyobayashi/emnapi/blob/main/packages/runtime/package.json

In there, it has `require` set as null, hence not conforming the expected shape of Entry in finder. 
```json
"./dist/emnapi.min.mjs": {
      "types": "./dist/emnapi.d.mts",
      "import": "./dist/emnapi.min.mjs",
      "require": null
    }
 ```

https://github.com/antongolub/tsc-esm-fix/blob/50ee19b9c39210a283b119ac983c5fac5e7956c1/src/main/ts/finder.ts#L62-L74

As a result, I got the following error when running `tsc-esm-fix` with my code
```
TypeError: Cannot convert undefined or null to object
│     at Function.values (<anonymous>)
│     at parseConditional
```

The reason is that with `null`, `Object.values(e)` will throw an error.

The solution is to check whether e is an object and if not skip parseConditional.

Shall we add a filter with entries?

**Comment by antongolub** [comment]
What an interesting case! We should definitely handle false like values.
