### ISSUE TITLE
support `..`

### ISSUE THREAD

**Issue by unional** [antongolub/tsc-esm-fix#80]
Thank you for making this package. 🌷 
I was thinking about making one like this myself. 😄 

I notice that `import ... from '..'` is not converted to `'../index.js'`. 😄

**Comment by unional** [comment]
![image](https://user-images.githubusercontent.com/3254987/172035151-2eb0b27d-b415-4623-8e23-3b31689206e4.png)

Also, I notice it occasionally will miss a few.

You can try it with this tag to flush out the issues: https://github.com/unional/type-plus/tree/v4.9.1

I'll be manually updating the remaining code and publish so the `main` branch will not have the non-fixed code.

**Comment by antongolub** [comment]
Hey, @unional 

`'..'`, nice catch, I'll fix this asap, thanks.

**Comment by unional** [comment]
> `--fillBlank` | Fill blank files with `export {}`. Does it help?

Um... mean this:

```ts
// foo.ts
export type Foo = string

// index.ts
import { Foo } from './foo' // this is not updated to `'./foo.js'`
```

**Comment by antongolub** [comment]
No idea what's wrong. Moreover, I've added a test exactly for this in #81: 

`src/test/fixtures/ts-project/src/main/ts/index.ts`
`index.ts` refers to `./only-types`.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5288046/172069390-d293e298-5d1f-4293-acbc-d0b565876cc1.png">

And the test is passed for both `--src` and `--target` opts.

```js
// tsc-esm-fix/src/test/ts/fix.ts
// Line 65
expect(read(resolve(temp, 't1/src/main/ts/index.ts'))).toMatchSnapshot()
```
gives
<img width="493" alt="image" src="https://user-images.githubusercontent.com/5288046/172069909-2a359df5-ed02-49f1-b181-348f40bb6478.png">

and
```js
...
// line 97
expect(read(resolve(temp, 'from/target/es6/index.mjs'))).toMatchSnapshot()
```
<img width="592" alt="image" src="https://user-images.githubusercontent.com/5288046/172069970-e8ebdd50-a96d-4a4e-a263-cd3ba4fe4988.png">
