### ISSUE TITLE
bug: types only containing file does not get ext for its ref

### ISSUE THREAD

**Issue by antongolub** [antongolub/tsc-esm-fix#82]
> `--fillBlank` | Fill blank files with `export {}`. Does it help?

Um... mean this:

```ts
// foo.ts
export type Foo = string

// index.ts
import { Foo } from './foo' // this is not updated to `'./foo.js'`
```

_Originally posted by @unional in https://github.com/antongolub/tsc-esm-fix/issues/80#issuecomment-1146877658_

**Comment by antongolub** [comment]
let's continue here

**Comment by antongolub** [comment]
> No idea what's wrong. Moreover, I've added a test exactly for this in #81:
> 
> `src/test/fixtures/ts-project/src/main/ts/index.ts` `index.ts` refers to `./only-types`.
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/5288046/172069390-d293e298-5d1f-4293-acbc-d0b565876cc1.png">
> 
> And the test is passed for both `--src` and `--target` opts.
> 
> ```js
> // tsc-esm-fix/src/test/ts/fix.ts
> // Line 65
> expect(read(resolve(temp, 't1/src/main/ts/index.ts'))).toMatchSnapshot()
> ```
> 
> gives <img alt="image" width="493" src="https://user-images.githubusercontent.com/5288046/172069909-2a359df5-ed02-49f1-b181-348f40bb6478.png">
> 
> and
> 
> ```js
> ...
> // line 97
> expect(read(resolve(temp, 'from/target/es6/index.mjs'))).toMatchSnapshot()
> ```
> 
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/5288046/172069970-e8ebdd50-a96d-4a4e-a263-cd3ba4fe4988.png">

**Comment by unional** [comment]
To make it easy to compare, I run `tsc-esm-fix` and pushed the before and after branches:

https://github.com/unional/type-plus/tree/esm-fix-before
https://github.com/unional/type-plus/tree/esm-fix-after

Here are the errors (including the '..' one):

```sh
     1  ts/array/index.ts:8
     3  ts/math/GreaterThan.ts:24
     1  ts/math/index.ts:2
     1  ts/nominal-types/index.ts:1
     1  ts/nominal-types/nominalMatch.ts:1
     1  ts/object/ANotB.ts:2
     1  ts/object/facade.ts:1
     1  ts/object/hasKey.ts:1
     7  ts/object/index.ts:2
     1  ts/object/IsDisjoint.ts:2
     1  ts/object/KeysWithDiffType.ts:3
     1  ts/object/mapProperties.ts:1
     1  ts/object/pick.ts:2
     1  ts/object/RecursiveIntersect.ts:1
     1  ts/object/RecursivePartial.ts:1
     1  ts/object/replaceProperty.ts:1
     1  ts/object/split.ts:2
     1  ts/object/typeOverrideIncompatible.ts:5
     1  ts/utils/index.ts:3
```

**Comment by antongolub** [comment]
run `tsc-esm-fix` with no opts, right?

**Comment by unional** [comment]
`yarn tsc-esm-fix --src=ts --target=ts --ext='.js'`

**Comment by unional** [comment]
btw, in the README, maybe you can mention using `tsc-esm-fix` directly with `npx` or `yarn dlx`.

That's probably the most common use case.

```sh
npx tsc-esm-fix --src=<src> --ext='.js'
```

**Comment by antongolub** [comment]
Just one missing symbol) The fix is on the way.

**Comment by antongolub** [comment]
@unional,

**Comment by unional** [comment]
👍 2.17.3 works.

**Comment by unional** [comment]
https://unional.github.io/typescript-guidelines/blog/2022-tsc-esm-fix

Happy coding~ 🌷
