### ISSUE TITLE
Filename in the source map file doesn't get updated when using `--ext`

### ISSUE THREAD

**Issue by alvis** [antongolub/tsc-esm-fix#86]
It's so great that if we run `tsc-esm-fix --target lib --ext .mjs`, this tool would update all `.js` modules files with an `.mjs` extension.

However, I notice that while the extension of the `.js` files get updated to `.mjs`, the file name in the source map file remains the old one with an `.js` extension, both inline or not.

**Comment by antongolub** [comment]
Sorry, It completelely ignores sourcemaps right now. Would you like to push PR for this feature?
