### ISSUE TITLE
from "./" for directory isn't correctly transformed

### ISSUE THREAD

**Issue by MirKml** [antongolub/tsc-esm-fix#87]
tsc-esm-fix is in mode of transformation compiled result from tsc. Result of tsc is javascript with this import
`import { Input, AutoComplete, Suggestion } from "./";`
It isn't transformed by tsc-esm-fix anyhow.

I think it's import from index - ./ means current directory.
So I expect this as result of tsc-esm-fix transformation.
`import { Input, AutoComplete, Suggestion } from "./index.js";`

**Comment by antongolub** [comment]
Oh, my fault. Trainling slash seems valid.

Thanks for the report.
