### ISSUE TITLE
__dirname conversion not working in Windows

### ISSUE THREAD

**Issue by unional** [antongolub/tsc-esm-fix#89]
The `__dirname` is converted to `/file:\/\/(.+)\/[^/]/.exec(import.meta.url)[1]`

However, in Windows, the `import.meta.url` looks like this:

`file:///D:/code/unional/clibuilder/packages/clibuilder/ts/loadPlugins.ts`

So the regex gives `/D:/code/unional/clibuilder/packages/clibuilder/ts/loadPlugins.ts`.

Having an extra `/` in front of the path.

**Comment by unional** [comment]
https://github.com/rhysd/dirname-filename-esm

Here is a package that that works

**Comment by antongolub** [comment]
Thanks for the bugreport. The right way is definetelly to use `fileURLToPath` (as [dirname-filename-esm](https://github.com/rhysd/dirname-filename-esm/blob/master/index.js) does), but it also requires an additional import inject  and we have to make sure that it hasn't been loaded in some way before. So let's tfirst ry to patch the regex:
```js
'/file:\\/{2,3}(.+)\\/[^/]/.exec(import.meta.url)[1]',
```

**Comment by antongolub** [comment]
@unional, could you plz test `2.20.1-beta.0`?

**Comment by unional** [comment]
```ts
/file:\/\/{2,3}(.+)\/[^/]/.exec(import.meta.url)![1]
```
btw I think it should be like this. with escapes and `!` to keep `tsc` quite. :)

**Comment by unional** [comment]
Yes, I think that works. 🎉

**Comment by antongolub** [comment]
`2.20.1` is on the way

**Comment by unional** [comment]
thx. Maybe you can also add the `!`. Right now we have to manually edit the file to add that in after transforming

**Comment by antongolub** [comment]
np, I will.
