### ISSUE TITLE
__dirname and __filename must be absolute at any platform

### ISSUE THREAD

**Issue by triadium** [antongolub/tsc-esm-fix#93]
Hello!
Awesome package! It helped me a lot when switching the project to ESM.

`${/file:\/{2,3}(.+)\/[^/]/.exec(import.meta.url)[1]}` removes leading slash and makes path relative on linux.
I fixed it like `${process.platform === 'win32' ? '' : '/'}${__dirname}`, but it would be nice to make auto replacing

**Comment by antongolub** [comment]
@triadium,

Thanks for reporting the bug. Do you want to provide a fix yourself?

**Comment by triadium** [comment]
@antongolub, 
Unfortunately, I can make PR only in month.

**Comment by antongolub** [comment]
Hey @triadium
What's new? Are you ready to continue?

**Comment by triadium** [comment]
Sorry that I did not reply for a while. Got a little sick.
I made a fix, opened the PR.
